title: 'Alecris Services'
default_lang: en
author:
  name: Alex
  email: alex.sterian.cristea@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Alecris Services offers you custom solutions for websites, web applications and more.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
